name: Automation-Android-CI/CD

on:
  workflow_call:
    inputs:
      reference:
        description: Reference to QA
        type: string
        required: true
    outputs:
      message:
        description: Message of QA result
        value: ${{ jobs.report.outputs.message }}
  workflow_dispatch:
    inputs:
      reference:
        description: Reference to QA
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo 'Build. reference : ${{ inputs.reference }}'

  qa:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check
        run: |
          echo qa

  report:
    runs-on: ubuntu-latest

    needs:
      - build
      - qa

    if: always() && (contains(needs.*.result, 'success') || contains(needs.*.result, 'failure'))
    outputs:
      message: ${{ steps.report-complete.outputs.message || steps.report-fail.outputs.message }}
    steps:
      - name: Report complete
        id: report-complete
        if: needs.qa.result == 'success'
        run: |
          echo "message=QA is completed!" >> $GITHUB_OUTPUT

      - name: Report fail
        id: report-fail
        if: needs.qa.result != 'success'
        run: |
          echo "message=QA is failed!" >> $GITHUB_OUTPUT